### ISSUE TITLE
Using the plugin to stream to RTSP server

### ISSUE THREAD

**Issue by dnshshkr** [basler/gst-plugin-pylon#69]
Hi, I'm planning to connect a color Basler camera to my Jetson Xavier NX with Cuda support. The Jetson will then host an RTSP server so that I can stream the camera output in gray on my computer. Does this plugin have RTSP server feature with the camera? If so, could you provide the command to do this? Thank you in advance.

My Jetson Xavier NX is running on JetPack 4.6 Ubuntu 18.04 with built-in Python 3.6

**Comment by michaelgruner** [comment]
The plugin itself just contains an element to capture from the camera. However, GStreamer offers a RTSP server you can use along with this element:gstreamer/subprojects/gst-rtsp-server at main · GStreamer/gstreamergithub.comThe simplest way to get started is to use one of their examples:gstreamer/subprojects/gst-rtsp-server/examples/test-launch.c at main · GStreamer/gstreamergithub.comMichaelOn 11 Nov 2023, at 08:38, Danish Shukor ***@***.***> wrote:﻿
Hi, I'm planning to connect a Basler camera with my Jetson Xavier NX with Cuda support. The Jetson will then host an RTSP server so that I can stream the camera output on my computer. Does this plugin have RTSP server feature with the camera? If so, could you provide the command to do this? Thank you in advance.

**Comment by dnshshkr** [comment]
Aite thank you!

**Comment by omerts** [comment]
@dnshshkr did you manage to get it to work? I am having trouble configuring it to work...
